[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.sqlite3", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.openssl"]

[phases.build]
cmds = ["echo 'PHP project - no build step required'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
